version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: toeic_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - toeic_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Application Service
  app:
    build: .
    container_name: toeic_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - toeic_network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

# Volumes
volumes:
  mysql_data:

# Networks
networks:
  toeic_network:
    driver: bridge